CREATE TABLE ESTR_MICH_RESTAURANTE (
    NOMBRE VARCHAR2(20),
    DIRECCION VARCHAR2(20),
    LOCALIDAD VARCHAR2(20),
    WEB VARCHAR2(75),
    ESTRELLAS NUMBER(2)
);

CREATE TABLE ESTR_MICH_RESTAURANTE_TELEFONO (
    NOMBRE VARCHAR2(20),
    TELEFONO VARCHAR2(12)
);

CREATE TABLE ESTR_MICH_RESTAURANTE_ANIO_EST (
    NOMBRE VARCHAR2(20),
    ANIO_EST NUMBER(4)
);

CREATE TABLE ESTR_MICH_RESTAURANTE_CHEF (
    NOMBRE VARCHAR2(20),
    CHEF VARCHAR2(20)
);

CREATE TABLE ESTR_MICH_CHEF (
    CHEF VARCHAR2(20),
    FEC_NAC DATE,
    IND_MAY_40 VARCHAR2(2),
    CIUDAD_NAC VARCHAR2(15)
);

-- a.
ALTER TABLE ESTR_MICH_RESTAURANTE ADD COD_RESTAURANTE NUMBER(3) 
CONSTRAINT PK_ESTR_MICH_RES_COD_RES PRIMARY KEY;

ALTER TABLE ESTR_MICH_RESTAURANTE DROP COLUMN NOMBRE

ALTER TABLE ESTR_MICH_RESTAURANTE_TELEFONO DROP COLUMN NOMBRE

ALTER TABLE ESTR_MICH_RESTAURANTE_ANIO_EST DROP COLUMN NOMBRE

ALTER TABLE ESTR_MICH_RESTAURANTE_CHEF DROP COLUMN NOMBRE

ALTER TABLE ESTR_MICH_RESTAURANTE_CHEF ADD COD_RESTAURANTE NUMBER(3) 
CONSTRAINT FK_EM_RES_CHEF_COD_RES REFERENCES ESTR_MICH_RESTAURANTE (COD_RESTAURANTE);

ALTER TABLE ESTR_MICH_RESTAURANTE_TELEFONO ADD COD_RESTAURANTE NUMBER(3) 
CONSTRAINT FK_EM_RES_TELF_COD_RES REFERENCES ESTR_MICH_RESTAURANTE (COD_RESTAURANTE);

ALTER TABLE ESTR_MICH_RESTAURANTE_ANIO_EST ADD COD_RESTAURANTE NUMBER(3) 
CONSTRAINT FK_EM_RES_ANIO_COD_RES REFERENCES ESTR_MICH_RESTAURANTE (COD_RESTAURANTE);

-- b.

ALTER TABLE ESTR_MICH_CHEF ADD COD_CHEF NUMBER(4) 
CONSTRAINT PK_EM_CHEF_COD_CHEF PRIMARY KEY;

ALTER TABLE ESTR_MICH_RESTAURANTE_CHEF DROP COLUMN CHEF;

ALTER TABLE ESTR_MICH_RESTAURANTE_CHEF ADD COD_CHEF NUMBER(4) 
CONSTRAINT FK_EM_RES_CHEF_COD_CHEF REFERENCES ESTR_MICH_CHEF (COD_CHEF);

ALTER TABLE ESTR_MICH_RESTAURANTE_TELEFONO ADD 
CONSTRAINT PK_EM_RES_TEL_COD_RES_TEL PRIMARY KEY (COD_RESTAURANTE, TELEFONO);

ALTER TABLE ESTR_MICH_RESTAURANTE_ANIO_EST ADD 
CONSTRAINT PK_EM_RES_ANIO_COD_RES_ANIO PRIMARY KEY (COD_RESTAURANTE, ANIO_EST);

-- C.

ALTER TABLE ESTR_MICH_RESTAURANTE ADD CONSTRAINT UQ_EM_RES_NOM UNIQUE (NOMBRE);

-- d.

ALTER TABLE ESTR_MICH_CHEF ADD CONSTRAINT UQ_EM_CHEF_CHEF UNIQUE (CHEF);

-- e.

ALTER TABLE ESTR_MICH_RESTAURANTE ADD CONSTRAINT CH_EM_RES_EST_POS CHECK (ESTRELLAS >= 0);

-- f.

ALTER TABLE ESTR_MICH_CHEF ADD CONSTRAINT CH_EM_CHEF_IND_DOM CHECK (IND_MAY_40 IN ('SI', 'NO'));